/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Mock CMS API
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customInstance } from '../../../scripts/fetcher';




/**
 * @summary Get pages
 */
export const getPages = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/pages`, method: 'GET', signal
    },
      );
    }
  



export const getGetPagesQueryKey = () => {
    return [
    `/pages`
    ] as const;
    }

    
export const getGetPagesQueryOptions = <TData = Awaited<ReturnType<typeof getPages>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPages>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPagesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPages>>> = ({ signal }) => getPages(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPages>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPagesQueryResult = NonNullable<Awaited<ReturnType<typeof getPages>>>
export type GetPagesQueryError = unknown


export function useGetPages<TData = Awaited<ReturnType<typeof getPages>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPages>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPages>>,
          TError,
          Awaited<ReturnType<typeof getPages>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPages<TData = Awaited<ReturnType<typeof getPages>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPages>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPages>>,
          TError,
          Awaited<ReturnType<typeof getPages>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPages<TData = Awaited<ReturnType<typeof getPages>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPages>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get pages
 */

export function useGetPages<TData = Awaited<ReturnType<typeof getPages>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPages>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPagesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get pages
 */
export const prefetchGetPagesQuery = async <TData = Awaited<ReturnType<typeof getPages>>, TError = unknown>(
 queryClient: QueryClient,  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPages>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetPagesQueryOptions(options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * @summary Get packages
 */
export const getPackages = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/packages`, method: 'GET', signal
    },
      );
    }
  



export const getGetPackagesQueryKey = () => {
    return [
    `/packages`
    ] as const;
    }

    
export const getGetPackagesQueryOptions = <TData = Awaited<ReturnType<typeof getPackages>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPackages>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPackagesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPackages>>> = ({ signal }) => getPackages(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPackages>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPackagesQueryResult = NonNullable<Awaited<ReturnType<typeof getPackages>>>
export type GetPackagesQueryError = unknown


export function useGetPackages<TData = Awaited<ReturnType<typeof getPackages>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPackages>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPackages>>,
          TError,
          Awaited<ReturnType<typeof getPackages>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPackages<TData = Awaited<ReturnType<typeof getPackages>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPackages>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPackages>>,
          TError,
          Awaited<ReturnType<typeof getPackages>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPackages<TData = Awaited<ReturnType<typeof getPackages>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPackages>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get packages
 */

export function useGetPackages<TData = Awaited<ReturnType<typeof getPackages>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPackages>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPackagesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get packages
 */
export const prefetchGetPackagesQuery = async <TData = Awaited<ReturnType<typeof getPackages>>, TError = unknown>(
 queryClient: QueryClient,  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPackages>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetPackagesQueryOptions(options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



