// This file is auto-generated by @hey-api/openapi-ts

import { type CancelablePromise, OpenAPI } from "@minecraft/requests";
import type { PostApiV1FilesUploadData, PostApiV1FilesUploadResponse } from "./types";
import { request as __request } from "@minecraft/requests/core/request";

export class DefaultService {
  /**
   * Upload
   * @param data The data for the request.
   * @param data.formData
   * @returns unknown Successful operation
   * @throws ApiError
   */
  public static postApiV1FilesUpload(
    data: PostApiV1FilesUploadData = {}
  ): CancelablePromise<PostApiV1FilesUploadResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/files/upload",
      formData: data.formData,
      mediaType: "multipart/form-data",
    });
  }
}
