name: "sample"
replicaCount: 1

ingressController: nginx

service:
  type: ClusterIP

domainName: "staging-front.chainmind.com"

app:
  url: "https://staging.innercircle-chainmind.com/"
  auth_trust_host: ""
  auth_secret: ""
  google_client_id: ""
  google_client_secret: ""

tls:
  enabled: false
  clusterIssuer: cloudflare
  secretName: staging-front-chainmind-tls

image:
  repository: registry.chainmind.com/frontiers/front
  pullPolicy: Always
  tag: latest

resources: {}
tolerations: {}
