import { MotionLazy } from "@/components/animate/motion-lazy";
import { LocalizationProvider } from "@/locales";
import { ThemeProvider } from "@/theme/theme-provider";
import type { Metadata } from "next";

import { Snackbar } from "@/components/snackbar";
import { getDictionary } from "@/locales/dictionary";
import { parsedCookies } from "@/utils/handleLanguageChange";
import { headers } from "next/headers";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import AuthProvider from "./_providers/AuthProvider";
import ProgressBarProvider from "./_providers/ProgressBarProvider";
import { StoreProvider } from "./_providers/StoreProvider";
import TanStackProvider from "./_providers/TanStackProvider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Chainmind",
  description: "Generated by bij7n/chainmind",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = await headers();
  const cookieHeader = headersList.get("cookie") || "";
  const cookies = parsedCookies(cookieHeader);
  const locale = cookies.lang || "en";

  const dict = await getDictionary(locale);
  const userAgent = headersList.get("user-agent");

  return (
    <StoreProvider dict={dict} userAgent={userAgent} currentLang={locale}>
      <html lang={locale}>
        <body style={{ backgroundColor: "#070720" }}>
          <AuthProvider>
            {/* <GoogleOAuthProvider clientId={googleProviderOption.clientId}> */}
            <TanStackProvider>
              <LocalizationProvider>
                <ThemeProvider>
                  <MotionLazy>
                    <Snackbar />
                    <ProgressBarProvider>
                      <NuqsAdapter>{children}</NuqsAdapter>
                    </ProgressBarProvider>
                  </MotionLazy>
                </ThemeProvider>
              </LocalizationProvider>
            </TanStackProvider>
            {/* </GoogleOAuthProvider> */}
          </AuthProvider>
        </body>
      </html>
    </StoreProvider>
  );
}
