import { MotionLazy } from '@/components/animate/motion-lazy';
import { LocalizationProvider } from '@/locales';
import { ThemeProvider } from '@/theme/theme-provider';
import type { Metadata } from 'next';
import './globals.css';

import { STORAGE_KEY, googleProviderOption } from '@/auth';
import { Snackbar } from '@/components/snackbar';
import { getDictionary } from '@/locales/dictionary';
import { parsedCookies } from '@/utils/handleLanguageChange';
import { GoogleOAuthProvider } from '@react-oauth/google';
import { headers } from 'next/headers';
import { NuqsAdapter } from 'nuqs/adapters/next/app';
import AuthProvider from './_providers/AuthProvider';
import ProgressBarProvider from './_providers/ProgressBarProvider';
import { StoreProvider } from './_providers/StoreProvider';
import TanStackProvider from './_providers/TanStackProvider';

export const metadata: Metadata = {
  title: 'Chainmind',
  description: 'Generated by bij7n/chainmind',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = await headers();
  const cookieHeader = headersList.get('cookie') || '';
  const cookies = parsedCookies(cookieHeader);
  const locale = cookies.lang || 'en';
  const accessToken = cookies[STORAGE_KEY];

  const dict = await getDictionary(locale);
  const userAgent = headersList.get('user-agent');

  return (
    <StoreProvider dict={dict} userAgent={userAgent} currentLang={locale}>
      <html lang={locale}>
        <body style={{ backgroundColor: '#070720' }}>
          <AuthProvider accessToken={accessToken}>
            <GoogleOAuthProvider clientId={googleProviderOption.clientId}>
              <TanStackProvider>
                <LocalizationProvider>
                  <ThemeProvider>
                    <MotionLazy>
                      <Snackbar />
                      <ProgressBarProvider />
                      <NuqsAdapter>{children}</NuqsAdapter>
                    </MotionLazy>
                  </ThemeProvider>
                </LocalizationProvider>
              </TanStackProvider>
            </GoogleOAuthProvider>
          </AuthProvider>
        </body>
      </html>
    </StoreProvider>
  );
}
