/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Mock Minecraft API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AffiliateHowItWorksResponse,
  AffiliateMeResponse,
  CoinReportCategoriesResponse,
  CoinReportResponse,
  GetCoinReportParams,
  GetFinancialPaymentsActive200,
  GetItems200,
  GlobalsDropZoneResponse,
  GlobalsLiveFeedResponse,
  GlobalsSocialMediaResponse,
  GlobalsVideoGlobalResponse,
  MeResponse,
  RoadmapsResponse
} from '../mockMinecraftAPI.schemas';

import { customInstance } from '../../../scripts/fetcher';




/**
 * @summary Add coin report favorite
 */
export const postCoinReportSlugFavorite = (
    slug: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/coin-report/${slug}/favorite`, method: 'POST', signal
    },
      );
    }
  


export const getPostCoinReportSlugFavoriteMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postCoinReportSlugFavorite>>, TError,{slug: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postCoinReportSlugFavorite>>, TError,{slug: string}, TContext> => {

const mutationKey = ['postCoinReportSlugFavorite'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postCoinReportSlugFavorite>>, {slug: string}> = (props) => {
          const {slug} = props ?? {};

          return  postCoinReportSlugFavorite(slug,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostCoinReportSlugFavoriteMutationResult = NonNullable<Awaited<ReturnType<typeof postCoinReportSlugFavorite>>>
    
    export type PostCoinReportSlugFavoriteMutationError = unknown

    /**
 * @summary Add coin report favorite
 */
export const usePostCoinReportSlugFavorite = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postCoinReportSlugFavorite>>, TError,{slug: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postCoinReportSlugFavorite>>,
        TError,
        {slug: string},
        TContext
      > => {

      const mutationOptions = getPostCoinReportSlugFavoriteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Remove coin report favorite
 */
export const deleteCoinReportSlugFavorite = (
    slug: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/coin-report/${slug}/favorite`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteCoinReportSlugFavoriteMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCoinReportSlugFavorite>>, TError,{slug: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteCoinReportSlugFavorite>>, TError,{slug: string}, TContext> => {

const mutationKey = ['deleteCoinReportSlugFavorite'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCoinReportSlugFavorite>>, {slug: string}> = (props) => {
          const {slug} = props ?? {};

          return  deleteCoinReportSlugFavorite(slug,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteCoinReportSlugFavoriteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCoinReportSlugFavorite>>>
    
    export type DeleteCoinReportSlugFavoriteMutationError = unknown

    /**
 * @summary Remove coin report favorite
 */
export const useDeleteCoinReportSlugFavorite = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCoinReportSlugFavorite>>, TError,{slug: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteCoinReportSlugFavorite>>,
        TError,
        {slug: string},
        TContext
      > => {

      const mutationOptions = getDeleteCoinReportSlugFavoriteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get coin report list
 */
export const getCoinReport = (
    params?: GetCoinReportParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<CoinReportResponse>(
      {url: `/coin-report`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetCoinReportQueryKey = (params?: GetCoinReportParams,) => {
    return [
    `/coin-report`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetCoinReportQueryOptions = <TData = Awaited<ReturnType<typeof getCoinReport>>, TError = unknown>(params?: GetCoinReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCoinReport>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCoinReportQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCoinReport>>> = ({ signal }) => getCoinReport(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCoinReport>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCoinReportQueryResult = NonNullable<Awaited<ReturnType<typeof getCoinReport>>>
export type GetCoinReportQueryError = unknown


export function useGetCoinReport<TData = Awaited<ReturnType<typeof getCoinReport>>, TError = unknown>(
 params: undefined |  GetCoinReportParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCoinReport>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCoinReport>>,
          TError,
          Awaited<ReturnType<typeof getCoinReport>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCoinReport<TData = Awaited<ReturnType<typeof getCoinReport>>, TError = unknown>(
 params?: GetCoinReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCoinReport>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCoinReport>>,
          TError,
          Awaited<ReturnType<typeof getCoinReport>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCoinReport<TData = Awaited<ReturnType<typeof getCoinReport>>, TError = unknown>(
 params?: GetCoinReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCoinReport>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get coin report list
 */

export function useGetCoinReport<TData = Awaited<ReturnType<typeof getCoinReport>>, TError = unknown>(
 params?: GetCoinReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCoinReport>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCoinReportQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get coin report categories
 */
export const getCoinReportCategories = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<CoinReportCategoriesResponse>(
      {url: `/coin-report/categories`, method: 'GET', signal
    },
      );
    }
  



export const getGetCoinReportCategoriesQueryKey = () => {
    return [
    `/coin-report/categories`
    ] as const;
    }

    
export const getGetCoinReportCategoriesQueryOptions = <TData = Awaited<ReturnType<typeof getCoinReportCategories>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCoinReportCategories>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCoinReportCategoriesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCoinReportCategories>>> = ({ signal }) => getCoinReportCategories(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCoinReportCategories>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCoinReportCategoriesQueryResult = NonNullable<Awaited<ReturnType<typeof getCoinReportCategories>>>
export type GetCoinReportCategoriesQueryError = unknown


export function useGetCoinReportCategories<TData = Awaited<ReturnType<typeof getCoinReportCategories>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCoinReportCategories>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCoinReportCategories>>,
          TError,
          Awaited<ReturnType<typeof getCoinReportCategories>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCoinReportCategories<TData = Awaited<ReturnType<typeof getCoinReportCategories>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCoinReportCategories>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCoinReportCategories>>,
          TError,
          Awaited<ReturnType<typeof getCoinReportCategories>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCoinReportCategories<TData = Awaited<ReturnType<typeof getCoinReportCategories>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCoinReportCategories>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get coin report categories
 */

export function useGetCoinReportCategories<TData = Awaited<ReturnType<typeof getCoinReportCategories>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCoinReportCategories>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCoinReportCategoriesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get global video content
 */
export const getGlobalsVideoGlobal = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<GlobalsVideoGlobalResponse>(
      {url: `/global-video-global`, method: 'GET', signal
    },
      );
    }
  



export const getGetGlobalsVideoGlobalQueryKey = () => {
    return [
    `/global-video-global`
    ] as const;
    }

    
export const getGetGlobalsVideoGlobalQueryOptions = <TData = Awaited<ReturnType<typeof getGlobalsVideoGlobal>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGlobalsVideoGlobal>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetGlobalsVideoGlobalQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getGlobalsVideoGlobal>>> = ({ signal }) => getGlobalsVideoGlobal(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getGlobalsVideoGlobal>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetGlobalsVideoGlobalQueryResult = NonNullable<Awaited<ReturnType<typeof getGlobalsVideoGlobal>>>
export type GetGlobalsVideoGlobalQueryError = unknown


export function useGetGlobalsVideoGlobal<TData = Awaited<ReturnType<typeof getGlobalsVideoGlobal>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGlobalsVideoGlobal>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGlobalsVideoGlobal>>,
          TError,
          Awaited<ReturnType<typeof getGlobalsVideoGlobal>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGlobalsVideoGlobal<TData = Awaited<ReturnType<typeof getGlobalsVideoGlobal>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGlobalsVideoGlobal>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGlobalsVideoGlobal>>,
          TError,
          Awaited<ReturnType<typeof getGlobalsVideoGlobal>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGlobalsVideoGlobal<TData = Awaited<ReturnType<typeof getGlobalsVideoGlobal>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGlobalsVideoGlobal>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get global video content
 */

export function useGetGlobalsVideoGlobal<TData = Awaited<ReturnType<typeof getGlobalsVideoGlobal>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGlobalsVideoGlobal>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetGlobalsVideoGlobalQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get global social media
 */
export const getGlobalsSocialMedia = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<GlobalsSocialMediaResponse>(
      {url: `/global-socialmedia`, method: 'GET', signal
    },
      );
    }
  



export const getGetGlobalsSocialMediaQueryKey = () => {
    return [
    `/global-socialmedia`
    ] as const;
    }

    
export const getGetGlobalsSocialMediaQueryOptions = <TData = Awaited<ReturnType<typeof getGlobalsSocialMedia>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGlobalsSocialMedia>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetGlobalsSocialMediaQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getGlobalsSocialMedia>>> = ({ signal }) => getGlobalsSocialMedia(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getGlobalsSocialMedia>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetGlobalsSocialMediaQueryResult = NonNullable<Awaited<ReturnType<typeof getGlobalsSocialMedia>>>
export type GetGlobalsSocialMediaQueryError = unknown


export function useGetGlobalsSocialMedia<TData = Awaited<ReturnType<typeof getGlobalsSocialMedia>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGlobalsSocialMedia>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGlobalsSocialMedia>>,
          TError,
          Awaited<ReturnType<typeof getGlobalsSocialMedia>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGlobalsSocialMedia<TData = Awaited<ReturnType<typeof getGlobalsSocialMedia>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGlobalsSocialMedia>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGlobalsSocialMedia>>,
          TError,
          Awaited<ReturnType<typeof getGlobalsSocialMedia>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGlobalsSocialMedia<TData = Awaited<ReturnType<typeof getGlobalsSocialMedia>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGlobalsSocialMedia>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get global social media
 */

export function useGetGlobalsSocialMedia<TData = Awaited<ReturnType<typeof getGlobalsSocialMedia>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGlobalsSocialMedia>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetGlobalsSocialMediaQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get roadmaps
 */
export const getRoadmaps = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<RoadmapsResponse>(
      {url: `/roadmaps`, method: 'GET', signal
    },
      );
    }
  



export const getGetRoadmapsQueryKey = () => {
    return [
    `/roadmaps`
    ] as const;
    }

    
export const getGetRoadmapsQueryOptions = <TData = Awaited<ReturnType<typeof getRoadmaps>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRoadmaps>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRoadmapsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRoadmaps>>> = ({ signal }) => getRoadmaps(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRoadmaps>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetRoadmapsQueryResult = NonNullable<Awaited<ReturnType<typeof getRoadmaps>>>
export type GetRoadmapsQueryError = unknown


export function useGetRoadmaps<TData = Awaited<ReturnType<typeof getRoadmaps>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRoadmaps>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRoadmaps>>,
          TError,
          Awaited<ReturnType<typeof getRoadmaps>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRoadmaps<TData = Awaited<ReturnType<typeof getRoadmaps>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRoadmaps>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRoadmaps>>,
          TError,
          Awaited<ReturnType<typeof getRoadmaps>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRoadmaps<TData = Awaited<ReturnType<typeof getRoadmaps>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRoadmaps>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get roadmaps
 */

export function useGetRoadmaps<TData = Awaited<ReturnType<typeof getRoadmaps>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRoadmaps>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetRoadmapsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get global live feed
 */
export const getGlobalsLiveFeed = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<GlobalsLiveFeedResponse>(
      {url: `/global-livefeed`, method: 'GET', signal
    },
      );
    }
  



export const getGetGlobalsLiveFeedQueryKey = () => {
    return [
    `/global-livefeed`
    ] as const;
    }

    
export const getGetGlobalsLiveFeedQueryOptions = <TData = Awaited<ReturnType<typeof getGlobalsLiveFeed>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGlobalsLiveFeed>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetGlobalsLiveFeedQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getGlobalsLiveFeed>>> = ({ signal }) => getGlobalsLiveFeed(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getGlobalsLiveFeed>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetGlobalsLiveFeedQueryResult = NonNullable<Awaited<ReturnType<typeof getGlobalsLiveFeed>>>
export type GetGlobalsLiveFeedQueryError = unknown


export function useGetGlobalsLiveFeed<TData = Awaited<ReturnType<typeof getGlobalsLiveFeed>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGlobalsLiveFeed>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGlobalsLiveFeed>>,
          TError,
          Awaited<ReturnType<typeof getGlobalsLiveFeed>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGlobalsLiveFeed<TData = Awaited<ReturnType<typeof getGlobalsLiveFeed>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGlobalsLiveFeed>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGlobalsLiveFeed>>,
          TError,
          Awaited<ReturnType<typeof getGlobalsLiveFeed>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGlobalsLiveFeed<TData = Awaited<ReturnType<typeof getGlobalsLiveFeed>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGlobalsLiveFeed>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get global live feed
 */

export function useGetGlobalsLiveFeed<TData = Awaited<ReturnType<typeof getGlobalsLiveFeed>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGlobalsLiveFeed>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetGlobalsLiveFeedQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get affiliate how it works
 */
export const getGlobalsAffiliateHowItWorks = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<AffiliateHowItWorksResponse>(
      {url: `/affiliate/how-it-works`, method: 'GET', signal
    },
      );
    }
  



export const getGetGlobalsAffiliateHowItWorksQueryKey = () => {
    return [
    `/affiliate/how-it-works`
    ] as const;
    }

    
export const getGetGlobalsAffiliateHowItWorksQueryOptions = <TData = Awaited<ReturnType<typeof getGlobalsAffiliateHowItWorks>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGlobalsAffiliateHowItWorks>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetGlobalsAffiliateHowItWorksQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getGlobalsAffiliateHowItWorks>>> = ({ signal }) => getGlobalsAffiliateHowItWorks(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getGlobalsAffiliateHowItWorks>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetGlobalsAffiliateHowItWorksQueryResult = NonNullable<Awaited<ReturnType<typeof getGlobalsAffiliateHowItWorks>>>
export type GetGlobalsAffiliateHowItWorksQueryError = unknown


export function useGetGlobalsAffiliateHowItWorks<TData = Awaited<ReturnType<typeof getGlobalsAffiliateHowItWorks>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGlobalsAffiliateHowItWorks>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGlobalsAffiliateHowItWorks>>,
          TError,
          Awaited<ReturnType<typeof getGlobalsAffiliateHowItWorks>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGlobalsAffiliateHowItWorks<TData = Awaited<ReturnType<typeof getGlobalsAffiliateHowItWorks>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGlobalsAffiliateHowItWorks>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGlobalsAffiliateHowItWorks>>,
          TError,
          Awaited<ReturnType<typeof getGlobalsAffiliateHowItWorks>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGlobalsAffiliateHowItWorks<TData = Awaited<ReturnType<typeof getGlobalsAffiliateHowItWorks>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGlobalsAffiliateHowItWorks>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get affiliate how it works
 */

export function useGetGlobalsAffiliateHowItWorks<TData = Awaited<ReturnType<typeof getGlobalsAffiliateHowItWorks>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGlobalsAffiliateHowItWorks>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetGlobalsAffiliateHowItWorksQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get current user
 */
export const getMe = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<MeResponse>(
      {url: `/auth/me`, method: 'GET', signal
    },
      );
    }
  



export const getGetMeQueryKey = () => {
    return [
    `/auth/me`
    ] as const;
    }

    
export const getGetMeQueryOptions = <TData = Awaited<ReturnType<typeof getMe>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMeQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMe>>> = ({ signal }) => getMe(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMeQueryResult = NonNullable<Awaited<ReturnType<typeof getMe>>>
export type GetMeQueryError = unknown


export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMe>>,
          TError,
          Awaited<ReturnType<typeof getMe>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMe>>,
          TError,
          Awaited<ReturnType<typeof getMe>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get current user
 */

export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get global drop zone
 */
export const getGlobalsDropZone = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<GlobalsDropZoneResponse>(
      {url: `/global-dropzone`, method: 'GET', signal
    },
      );
    }
  



export const getGetGlobalsDropZoneQueryKey = () => {
    return [
    `/global-dropzone`
    ] as const;
    }

    
export const getGetGlobalsDropZoneQueryOptions = <TData = Awaited<ReturnType<typeof getGlobalsDropZone>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGlobalsDropZone>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetGlobalsDropZoneQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getGlobalsDropZone>>> = ({ signal }) => getGlobalsDropZone(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getGlobalsDropZone>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetGlobalsDropZoneQueryResult = NonNullable<Awaited<ReturnType<typeof getGlobalsDropZone>>>
export type GetGlobalsDropZoneQueryError = unknown


export function useGetGlobalsDropZone<TData = Awaited<ReturnType<typeof getGlobalsDropZone>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGlobalsDropZone>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGlobalsDropZone>>,
          TError,
          Awaited<ReturnType<typeof getGlobalsDropZone>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGlobalsDropZone<TData = Awaited<ReturnType<typeof getGlobalsDropZone>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGlobalsDropZone>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGlobalsDropZone>>,
          TError,
          Awaited<ReturnType<typeof getGlobalsDropZone>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGlobalsDropZone<TData = Awaited<ReturnType<typeof getGlobalsDropZone>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGlobalsDropZone>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get global drop zone
 */

export function useGetGlobalsDropZone<TData = Awaited<ReturnType<typeof getGlobalsDropZone>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGlobalsDropZone>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetGlobalsDropZoneQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get affiliate me
 */
export const getAffiliateMe = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<AffiliateMeResponse>(
      {url: `/affiliate/me`, method: 'GET', signal
    },
      );
    }
  



export const getGetAffiliateMeQueryKey = () => {
    return [
    `/affiliate/me`
    ] as const;
    }

    
export const getGetAffiliateMeQueryOptions = <TData = Awaited<ReturnType<typeof getAffiliateMe>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAffiliateMe>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAffiliateMeQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAffiliateMe>>> = ({ signal }) => getAffiliateMe(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAffiliateMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAffiliateMeQueryResult = NonNullable<Awaited<ReturnType<typeof getAffiliateMe>>>
export type GetAffiliateMeQueryError = unknown


export function useGetAffiliateMe<TData = Awaited<ReturnType<typeof getAffiliateMe>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAffiliateMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAffiliateMe>>,
          TError,
          Awaited<ReturnType<typeof getAffiliateMe>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAffiliateMe<TData = Awaited<ReturnType<typeof getAffiliateMe>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAffiliateMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAffiliateMe>>,
          TError,
          Awaited<ReturnType<typeof getAffiliateMe>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAffiliateMe<TData = Awaited<ReturnType<typeof getAffiliateMe>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAffiliateMe>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get affiliate me
 */

export function useGetAffiliateMe<TData = Awaited<ReturnType<typeof getAffiliateMe>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAffiliateMe>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAffiliateMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get items
 */
export const getItems = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<GetItems200>(
      {url: `/items`, method: 'GET', signal
    },
      );
    }
  



export const getGetItemsQueryKey = () => {
    return [
    `/items`
    ] as const;
    }

    
export const getGetItemsQueryOptions = <TData = Awaited<ReturnType<typeof getItems>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItems>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetItemsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getItems>>> = ({ signal }) => getItems(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getItems>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetItemsQueryResult = NonNullable<Awaited<ReturnType<typeof getItems>>>
export type GetItemsQueryError = unknown


export function useGetItems<TData = Awaited<ReturnType<typeof getItems>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItems>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getItems>>,
          TError,
          Awaited<ReturnType<typeof getItems>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetItems<TData = Awaited<ReturnType<typeof getItems>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItems>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getItems>>,
          TError,
          Awaited<ReturnType<typeof getItems>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetItems<TData = Awaited<ReturnType<typeof getItems>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItems>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get items
 */

export function useGetItems<TData = Awaited<ReturnType<typeof getItems>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItems>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetItemsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get active payment
 */
export const getFinancialPaymentsActive = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<GetFinancialPaymentsActive200>(
      {url: `/financial/payments/active`, method: 'GET', signal
    },
      );
    }
  



export const getGetFinancialPaymentsActiveQueryKey = () => {
    return [
    `/financial/payments/active`
    ] as const;
    }

    
export const getGetFinancialPaymentsActiveQueryOptions = <TData = Awaited<ReturnType<typeof getFinancialPaymentsActive>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFinancialPaymentsActive>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetFinancialPaymentsActiveQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getFinancialPaymentsActive>>> = ({ signal }) => getFinancialPaymentsActive(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getFinancialPaymentsActive>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetFinancialPaymentsActiveQueryResult = NonNullable<Awaited<ReturnType<typeof getFinancialPaymentsActive>>>
export type GetFinancialPaymentsActiveQueryError = unknown


export function useGetFinancialPaymentsActive<TData = Awaited<ReturnType<typeof getFinancialPaymentsActive>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFinancialPaymentsActive>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFinancialPaymentsActive>>,
          TError,
          Awaited<ReturnType<typeof getFinancialPaymentsActive>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFinancialPaymentsActive<TData = Awaited<ReturnType<typeof getFinancialPaymentsActive>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFinancialPaymentsActive>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFinancialPaymentsActive>>,
          TError,
          Awaited<ReturnType<typeof getFinancialPaymentsActive>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFinancialPaymentsActive<TData = Awaited<ReturnType<typeof getFinancialPaymentsActive>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFinancialPaymentsActive>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get active payment
 */

export function useGetFinancialPaymentsActive<TData = Awaited<ReturnType<typeof getFinancialPaymentsActive>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFinancialPaymentsActive>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetFinancialPaymentsActiveQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




