/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Mock Minecraft API
 * OpenAPI spec version: 1.0.0
 */
export interface CoinReportFavoriteResponse {
  success?: boolean;
}

export type CoinReportResponseMeta = {
  next_update?: number;
  total_count?: number;
};

export interface CoinReportResponse {
  data?: CoinReportItem[];
  meta?: CoinReportResponseMeta;
}

export interface CoinReportItem {
  id?: string;
  name?: string;
  price?: number;
  category?: string;
  signal?: string;
}

export interface CoinReportCategoriesResponse {
  data?: CoinReportCategory[];
}

export interface CoinReportCategory {
  name?: string;
  slug?: string;
}

export type GlobalsVideoGlobalResponseData = {
  videos?: VideoGlobalItem[];
};

export interface GlobalsVideoGlobalResponse {
  data?: GlobalsVideoGlobalResponseData;
}

export interface VideoGlobalItem {
  title?: string;
  videoLink?: string;
  videoPage?: string;
}

export type GlobalsSocialMediaResponseData = {
  socialLinks?: SocialLink[];
};

export interface GlobalsSocialMediaResponse {
  data?: GlobalsSocialMediaResponseData;
}

export type SocialLinkIcon = {
  url?: string;
};

export interface SocialLink {
  id?: string;
  name?: string;
  url?: string;
  icon?: SocialLinkIcon;
}

export type RoadmapsResponseData = {
  docs: RoadmapItem[];
};

export interface RoadmapsResponse {
  data?: RoadmapsResponseData;
}

export type RoadmapItemImageSizesRoadmap = {
  url?: string;
};

export type RoadmapItemImageSizes = {
  roadmap?: RoadmapItemImageSizesRoadmap;
};

export type RoadmapItemImage = {
  sizes?: RoadmapItemImageSizes;
};

export interface RoadmapItem {
  title: string;
  dateOnly: string;
  descriptionText: string;
  status: string;
  image?: RoadmapItemImage;
}

export type GlobalsLiveFeedResponseData = {
  author: string;
  title: string;
  text: string;
};

export interface GlobalsLiveFeedResponse {
  data?: GlobalsLiveFeedResponseData;
}

export interface MeResponse {
  data?: User;
}

export type UserBusinessInfoAnyOf = {
  address?: string;
  city?: string;
  company_name?: string;
  country?: string;
  email?: string;
  holder_name?: string;
  zip_code?: string;
  vat_number?: string;
  registration_number?: string;
  created_at?: string;
};

export type UserBusinessInfo = UserBusinessInfoAnyOf | null;

export interface User {
  id: string;
  email: string;
  avatar_url?: string;
  full_name?: string;
  kyc_status?: boolean;
  plan_type?: string;
  rank_type?: string;
  has_2fa?: boolean;
  banned?: boolean;
  suspended?: boolean;
  telegram_group_joined?: boolean;
  telegram_id?: string;
  business_info?: UserBusinessInfo;
}

export type AffiliateHowItWorksResponseData = {
  layout?: CMSBlock[];
};

export interface AffiliateHowItWorksResponse {
  data?: AffiliateHowItWorksResponseData;
}

export type CMSBlockLayoutItem = { [key: string]: unknown };

export interface CMSBlock {
  blockType?: string;
  blockTitle?: string;
  title?: string;
  text?: string;
  buttonText?: string;
  buttonLink?: string;
  layout?: CMSBlockLayoutItem[];
}

export type GlobalsDropZoneResponseDataStatus = typeof GlobalsDropZoneResponseDataStatus[keyof typeof GlobalsDropZoneResponseDataStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GlobalsDropZoneResponseDataStatus = {
  active: 'active',
  inactive: 'inactive',
} as const;

export type GlobalsDropZoneResponseData = {
  status?: GlobalsDropZoneResponseDataStatus;
  message?: string;
  timestampUnix?: number;
  coins?: DropZoneCoin[];
};

export interface GlobalsDropZoneResponse {
  data?: GlobalsDropZoneResponseData;
}

export type DropZoneCoinIcon = {
  url?: string;
};

export type DropZoneCoinMembershipItem = {
  slug?: string;
};

export interface DropZoneCoin {
  name: string;
  cmrValue: number;
  potentialMultiplicator: number;
  icon?: DropZoneCoinIcon;
  membership?: DropZoneCoinMembershipItem[];
}

export type AffiliateMeResponseDataRank = {
  type?: string;
  percent?: number;
};

export type AffiliateMeResponseDataNextRank = {
  gold_coins?: number;
};

export type AffiliateMeResponseData = {
  turnover?: number;
  agreed_to_tos?: boolean;
  goldCoins?: number;
  rank?: AffiliateMeResponseDataRank;
  next_rank?: AffiliateMeResponseDataNextRank;
};

export interface AffiliateMeResponse {
  data?: AffiliateMeResponseData;
}

export type GetCoinReportParams = {
opts?: string;
};

export type GetItems200DataItem = {
  id: string;
  name: string;
  price: number;
};

export type GetItems200 = {
  data?: GetItems200DataItem[];
};

export type GetFinancialPaymentsActive200Data = {
  id: string;
  plan_type: string;
  status: string;
};

export type GetFinancialPaymentsActive200 = {
  data?: GetFinancialPaymentsActive200Data;
};

