// This file is auto-generated by @hey-api/openapi-ts

import type { PostApiV1FilesUploadData } from './types';

import { customInstance } from '@/scripts/fetcher';
import type { HttpStatusResponse } from '@/services/minecraft/minecraftAPI.schemas';

export class DefaultService {
  /**
   * Upload
   * @param data The data for the request.
   * @param data.formData
   * @returns unknown Successful operation
   * @throws ApiError
   */
  public static postApiV1FilesUpload(
    data: PostApiV1FilesUploadData = {}
  ): Promise<HttpStatusResponse> {
    return customInstance({
      url: '/files/upload',
      headers: { 'Content-Type': 'multipart/form-data' },
      method: 'POST',
      data: data.formData,
    });
  }
}
