export const mockData = [
  {
    id: "1",
    logo: "https://st4.depositphotos.com/17740994/19754/v/1600/depositphotos_197540300-stock-illustration-bitcoin-logo-on-transparrent-background.jpg",
    name: "Aquatic Wonders",
    symbol: "AWND",
    package: "fish",
    category: "Seafood",
    cmr: 2.1,
    ee_signal: 8.5,
    potential_multiplicator: 1.9,
    rtl: 0.8,
    risk_level: "Medium",
    current_price: 28.4,
  },
  {
    id: "12",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Bitcoin.svg/64px-Bitcoin.svg",
    name: "Shrimp Global",
    symbol: "SGLO",
    package: "shrimp",
    category: "Seafood",
    cmr: 1.75,
    ee_signal: 10.0,
    potential_multiplicator: 2.2,
    rtl: 0.7,
    risk_level: "Low",
    current_price: 12.99,
  },
  {
    id: "13",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Bitcoin.svg/64px-Bitcoin.svg",
    name: "Whale Dynamics",
    symbol: "WDYN",
    package: "whale",
    category: "Marine",
    cmr: 3.5,
    ee_signal: 15.3,
    potential_multiplicator: 4.0,
    rtl: 0.95,
    risk_level: "High",
    current_price: 85.0,
  },
  {
    id: "14",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Bitcoin.svg/64px-Bitcoin.svg",
    name: "Plankton Innovators",
    symbol: "PLNK",
    package: "plankton",
    category: "Marine Biology",
    cmr: 1.2,
    ee_signal: 5.8,
    potential_multiplicator: 1.5,
    rtl: 0.6,
    risk_level: "Very Low",
    current_price: 5.5,
  },
  {
    id: "15",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Bitcoin.svg/64px-Bitcoin.svg",
    name: "Shark Enterprises",
    symbol: "SHRK",
    package: "shark",
    category: "Predatory Fish",
    cmr: 2.8,
    ee_signal: 11.0,
    potential_multiplicator: 3.5,
    rtl: 0.88,
    risk_level: "Medium",
    current_price: 60.0,
  },
  // Add more entries as needed
];
